
CREATE TABLE IF NOT EXISTS garcom(
    id BIGINT PRIMARY KEY,
    cargo ENUM('RESPONSAVEL','ATENDENTE') NOT NULL,
    CONSTRAINT fk_garcom_usuario
    FOREIGN KEY(id)
    REFERENCES usuario(id)
    ON DELETE CASCADE

);